name: message_list
description: "A  Flutter message list package"
version: 1.0.0
homepage: https://github.com/leesama/message_list
documentation: https://github.com/leesama/message_list/blob/main/README.md


environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bubble: ^1.2.1
  flutter:
    sdk: flutter
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

